spring:
  application:
    name: Project_Spring_Hotel

  datasource:
    url: jdbc:mysql://localhost:3306/project_db
    username: root
    password: p123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      file-size-threshold: 2MB

server:
  port: 9192